
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ASSIGN_ID (result) = COPYTRAV (ASSIGN_ID (arg_node), arg_info);
  ASSIGN_EXPR (result) = COPYTRAV (ASSIGN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OP (result) = BINOP_OP (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbool (node * arg_node, info * arg_info)
{
  node *result = TBmakeBool (FALSE);
  DBUG_ENTER ("COPYbool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOL_VALUE (result) = BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYcast
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYcast (node * arg_node, info * arg_info)
{
  node *result = TBmakeCast (BT_unknown, NULL);
  DBUG_ENTER ("COPYcast");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  CAST_CASTTYPE (result) = CAST_CASTTYPE (arg_node);
  /* Copy sons */
  CAST_EXPR (result) = COPYTRAV (CAST_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdeclarations
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Declarations node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdeclarations (node * arg_node, info * arg_info)
{
  node *result = TBmakeDeclarations (NULL, NULL);
  DBUG_ENTER ("COPYdeclarations");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DECLARATIONS_DECLARATION (result) =
    COPYTRAV (DECLARATIONS_DECLARATION (arg_node), arg_info);
  DECLARATIONS_NEXT (result) =
    COPYTRAV (DECLARATIONS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdowhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdowhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeDowhile (NULL, NULL);
  DBUG_ENTER ("COPYdowhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DOWHILE_EXPR (result) = COPYTRAV (DOWHILE_EXPR (arg_node), arg_info);
  DOWHILE_BLOCK (result) = COPYTRAV (DOWHILE_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYerror (node * arg_node, info * arg_info)
{
  node *result = TBmakeError (NULL, PH_initial, NULL);
  DBUG_ENTER ("COPYerror");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ERROR_MESSAGE (result) = STRcpy (ERROR_MESSAGE (arg_node));
  ERROR_ANYPHASE (result) = ERROR_ANYPHASE (arg_node);
  /* Copy sons */
  ERROR_NEXT (result) = COPYTRAV (ERROR_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYexprs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Exprs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYexprs (node * arg_node, info * arg_info)
{
  node *result = TBmakeExprs (NULL, NULL);
  DBUG_ENTER ("COPYexprs");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  EXPRS_FIRST (result) = COPYTRAV (EXPRS_FIRST (arg_node), arg_info);
  EXPRS_NEXT (result) = COPYTRAV (EXPRS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloat (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloat ();
  DBUG_ENTER ("COPYfloat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOAT_VALUE (result) = FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfor (node * arg_node, info * arg_info)
{
  node *result = TBmakeFor (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYfor");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FOR_ASSIGN (result) = COPYTRAV (FOR_ASSIGN (arg_node), arg_info);
  FOR_EXPRSTOP (result) = COPYTRAV (FOR_EXPRSTOP (arg_node), arg_info);
  FOR_EXPRINCR (result) = COPYTRAV (FOR_EXPRINCR (arg_node), arg_info);
  FOR_BLOCK (result) = COPYTRAV (FOR_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunbody (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunbody (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfunbody");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNBODY_VARDECS (result) = COPYTRAV (FUNBODY_VARDECS (arg_node), arg_info);
  FUNBODY_LOCALFUNDEFS (result) =
    COPYTRAV (FUNBODY_LOCALFUNDEFS (arg_node), arg_info);
  FUNBODY_STATEMENTS (result) =
    COPYTRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfuncall
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfuncall (node * arg_node, info * arg_info)
{
  node *result = TBmakeFuncall (NULL, NULL);
  DBUG_ENTER ("COPYfuncall");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNCALL_ID (result) = COPYTRAV (FUNCALL_ID (arg_node), arg_info);
  FUNCALL_EXPRS (result) = COPYTRAV (FUNCALL_EXPRS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundec (NULL);
  DBUG_ENTER ("COPYfundec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNDEC_FUNHEADER (result) =
    COPYTRAV (FUNDEC_FUNHEADER (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundef (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundef (FALSE, NULL, NULL);
  DBUG_ENTER ("COPYfundef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNDEF_EXPORT (result) = FUNDEF_EXPORT (arg_node);
  /* Copy sons */
  FUNDEF_HEADER (result) = COPYTRAV (FUNDEF_HEADER (arg_node), arg_info);
  FUNDEF_BODY (result) = COPYTRAV (FUNDEF_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunheader
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunHeader node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunheader (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunheader (, NULL, NULL);
  DBUG_ENTER ("COPYfunheader");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNHEADER_RETTYPE (result) = STRcpy (FUNHEADER_RETTYPE (arg_node));
  /* Copy sons */
  FUNHEADER_PARAMS (result) =
    COPYTRAV (FUNHEADER_PARAMS (arg_node), arg_info);
  FUNHEADER_ID (result) = COPYTRAV (FUNHEADER_ID (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldec (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldec (BT_unknown, NULL);
  DBUG_ENTER ("COPYglobaldec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  GLOBALDEC_TYPE (result) = GLOBALDEC_TYPE (arg_node);
  /* Copy sons */
  GLOBALDEC_ID (result) = COPYTRAV (GLOBALDEC_ID (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYglobaldef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node GlobalDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYglobaldef (node * arg_node, info * arg_info)
{
  node *result = TBmakeGlobaldef (BT_unknown, FALSE, NULL, NULL);
  DBUG_ENTER ("COPYglobaldef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  GLOBALDEF_TYPE (result) = GLOBALDEF_TYPE (arg_node);
  GLOBALDEF_EXPORT (result) = GLOBALDEF_EXPORT (arg_node);
  /* Copy sons */
  GLOBALDEF_ID (result) = COPYTRAV (GLOBALDEF_ID (arg_node), arg_info);
  GLOBALDEF_EXPR (result) = COPYTRAV (GLOBALDEF_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYid
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Id node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYid (node * arg_node, info * arg_info)
{
  node *result = TBmakeId ();
  DBUG_ENTER ("COPYid");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ID_NAME (result) = STRcpy (ID_NAME (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYif
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYif (node * arg_node, info * arg_info)
{
  node *result = TBmakeIf (NULL, NULL, NULL);
  DBUG_ENTER ("COPYif");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  IF_EXPR (result) = COPYTRAV (IF_EXPR (arg_node), arg_info);
  IF_BLOCK (result) = COPYTRAV (IF_BLOCK (arg_node), arg_info);
  IF_ELSEBLOCK (result) = COPYTRAV (IF_ELSEBLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYlocalfundef
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node LocalFunDef node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYlocalfundef (node * arg_node, info * arg_info)
{
  node *result = TBmakeLocalfundef (NULL, NULL);
  DBUG_ENTER ("COPYlocalfundef");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  LOCALFUNDEF_HEADER (result) =
    COPYTRAV (LOCALFUNDEF_HEADER (arg_node), arg_info);
  LOCALFUNDEF_BODY (result) =
    COPYTRAV (LOCALFUNDEF_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYlocalfundefs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node LocalFunDefs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYlocalfundefs (node * arg_node, info * arg_info)
{
  node *result = TBmakeLocalfundefs (NULL, NULL);
  DBUG_ENTER ("COPYlocalfundefs");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  LOCALFUNDEFS_FIRST (result) =
    COPYTRAV (LOCALFUNDEFS_FIRST (arg_node), arg_info);
  LOCALFUNDEFS_NEXT (result) =
    COPYTRAV (LOCALFUNDEFS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmonop (node * arg_node, info * arg_info)
{
  node *result = TBmakeMonop (, NULL);
  DBUG_ENTER ("COPYmonop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MONOP_OP (result) = STRcpy (MONOP_OP (arg_node));
  /* Copy sons */
  MONOP_EXPR (result) = COPYTRAV (MONOP_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYnum (node * arg_node, info * arg_info)
{
  node *result = TBmakeNum (0);
  DBUG_ENTER ("COPYnum");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  NUM_VALUE (result) = NUM_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Param node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparam (node * arg_node, info * arg_info)
{
  node *result = TBmakeParam (BT_unknown, NULL);
  DBUG_ENTER ("COPYparam");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  PARAM_TYPE (result) = PARAM_TYPE (arg_node);
  /* Copy sons */
  PARAM_ID (result) = COPYTRAV (PARAM_ID (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYparams
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Params node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYparams (node * arg_node, info * arg_info)
{
  node *result = TBmakeParams (NULL, NULL);
  DBUG_ENTER ("COPYparams");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  PARAMS_FIRST (result) = COPYTRAV (PARAMS_FIRST (arg_node), arg_info);
  PARAMS_NEXT (result) = COPYTRAV (PARAMS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYreturn (node * arg_node, info * arg_info)
{
  node *result = TBmakeReturn (NULL);
  DBUG_ENTER ("COPYreturn");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  RETURN_EXPR (result) = COPYTRAV (RETURN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstmts
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstmts (node * arg_node, info * arg_info)
{
  node *result = TBmakeStmts (NULL, NULL);
  DBUG_ENTER ("COPYstmts");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STMTS_STMT (result) = COPYTRAV (STMTS_STMT (arg_node), arg_info);
  STMTS_NEXT (result) = COPYTRAV (STMTS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardec (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardec (BT_unknown, NULL, NULL);
  DBUG_ENTER ("COPYvardec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARDEC_TYPE (result) = VARDEC_TYPE (arg_node);
  /* Copy sons */
  VARDEC_ID (result) = COPYTRAV (VARDEC_ID (arg_node), arg_info);
  VARDEC_EXPR (result) = COPYTRAV (VARDEC_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardecs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDecs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardecs (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardecs (NULL, NULL);
  DBUG_ENTER ("COPYvardecs");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  VARDECS_FIRST (result) = COPYTRAV (VARDECS_FIRST (arg_node), arg_info);
  VARDECS_NEXT (result) = COPYTRAV (VARDECS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYwhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeWhile (NULL, NULL);
  DBUG_ENTER ("COPYwhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  WHILE_EXPR (result) = COPYTRAV (WHILE_EXPR (arg_node), arg_info);
  WHILE_BLOCK (result) = COPYTRAV (WHILE_BLOCK (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
