
/**
 * @file node_basic.c
 *
 * Functions to allocate node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: node_basic.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "node_basic.h"
#include "tree_basic.h"
#include "memory.h"
#include "dbug.h"
#include "globals.h"
#include "ctinfo.h"

static node *
MakeEmptyNode ()
{
  node *result;

  DBUG_ENTER ("MakeEmptyNode");

  result = (node *) MEMmalloc (sizeof (node));

  NODE_LINE (result) = global.line;
  NODE_COL (result) = global.col;

  DBUG_RETURN (result);
}



/*****************************************************************************
 * N_Declarations :
 *****************************************************************************/

node *
TBmakeDeclarations (node * Declaration, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeDeclarations");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_declarations = MEMmalloc (sizeof (struct SONS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_declarations =
    MEMmalloc (sizeof (struct ATTRIBS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE",
	      ("assigning son Declaration initial value: %s ", Declaration));
  DECLARATIONS_DECLARATION (this) = Declaration;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  DECLARATIONS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((DECLARATIONS_DECLARATION (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_fundec)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_fundef)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_globaldec)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_globaldef))
    {
      CTIwarn
	("Field Declaration of node N_Declarations has non-allowed target node.");
    }
  if ((DECLARATIONS_NEXT (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_NEXT (this)) != N_declarations))
    {
      CTIwarn
	("Field Next of node N_Declarations has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunDec :
 *****************************************************************************/

node *
TBmakeFundec (node * FunHeader)
{
  node *this;
  DBUG_ENTER ("TBmakeFundec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_fundec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_fundec = MEMmalloc (sizeof (struct SONS_N_FUNDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_fundec = MEMmalloc (sizeof (struct ATTRIBS_N_FUNDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_fundec;
  DBUG_PRINT ("MAKE",
	      ("assigning son FunHeader initial value: %s ", FunHeader));
  FUNDEC_FUNHEADER (this) = FunHeader;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNDEC_FUNHEADER (this) != NULL)
      && (NODE_TYPE (FUNDEC_FUNHEADER (this)) != N_funheader))
    {
      CTIwarn
	("Field FunHeader of node N_FunDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunDef :
 *****************************************************************************/

node *
TBmakeFundef (bool Export, node * Header, node * Body)
{
  node *this;
  DBUG_ENTER ("TBmakeFundef");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_fundef;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_fundef = MEMmalloc (sizeof (struct SONS_N_FUNDEF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_fundef = MEMmalloc (sizeof (struct ATTRIBS_N_FUNDEF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_fundef;
  DBUG_PRINT ("MAKE", ("assigning son Header initial value: %s ", Header));
  FUNDEF_HEADER (this) = Header;
  DBUG_PRINT ("MAKE", ("assigning son Body initial value: %s ", Body));
  FUNDEF_BODY (this) = Body;
  FUNDEF_EXPORT (this) = Export;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNDEF_HEADER (this) != NULL)
      && (NODE_TYPE (FUNDEF_HEADER (this)) != N_funheader))
    {
      CTIwarn ("Field Header of node N_FunDef has non-allowed target node.");
    }
  if ((FUNDEF_BODY (this) != NULL)
      && (NODE_TYPE (FUNDEF_BODY (this)) != N_funbody))
    {
      CTIwarn ("Field Body of node N_FunDef has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunHeader :
 *****************************************************************************/

node *
TBmakeFunheader (RetType, node * Params, node * Id)
{
  node *this;
  DBUG_ENTER ("TBmakeFunheader");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funheader;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funheader = MEMmalloc (sizeof (struct SONS_N_FUNHEADER));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funheader = MEMmalloc (sizeof (struct ATTRIBS_N_FUNHEADER));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funheader;
  DBUG_PRINT ("MAKE", ("assigning son Params initial value: %s ", Params));
  FUNHEADER_PARAMS (this) = Params;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  FUNHEADER_ID (this) = Id;
  FUNHEADER_RETTYPE (this) = RetType;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNHEADER_PARAMS (this) != NULL)
      && (NODE_TYPE (FUNHEADER_PARAMS (this)) != N_params))
    {
      CTIwarn
	("Field Params of node N_FunHeader has non-allowed target node.");
    }
  if ((FUNHEADER_ID (this) != NULL)
      && (NODE_TYPE (FUNHEADER_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_FunHeader has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunBody :
 *****************************************************************************/

node *
TBmakeFunbody (node * VarDecs, node * LocalFunDefs, node * Statements)
{
  node *this;
  DBUG_ENTER ("TBmakeFunbody");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funbody = MEMmalloc (sizeof (struct SONS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funbody = MEMmalloc (sizeof (struct ATTRIBS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("assigning son VarDecs initial value: %s ", VarDecs));
  FUNBODY_VARDECS (this) = VarDecs;
  DBUG_PRINT ("MAKE",
	      ("assigning son LocalFunDefs initial value: %s ",
	       LocalFunDefs));
  FUNBODY_LOCALFUNDEFS (this) = LocalFunDefs;
  DBUG_PRINT ("MAKE",
	      ("assigning son Statements initial value: %s ", Statements));
  FUNBODY_STATEMENTS (this) = Statements;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNBODY_VARDECS (this) != NULL)
      && (NODE_TYPE (FUNBODY_VARDECS (this)) != N_vardecs))
    {
      CTIwarn
	("Field VarDecs of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_LOCALFUNDEFS (this) != NULL)
      && (NODE_TYPE (FUNBODY_LOCALFUNDEFS (this)) != N_localfundefs))
    {
      CTIwarn
	("Field LocalFunDefs of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_STATEMENTS (this) != NULL)
      && (NODE_TYPE (FUNBODY_STATEMENTS (this)) != N_stmts))
    {
      CTIwarn
	("Field Statements of node N_FunBody has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_VarDecs :
 *****************************************************************************/

node *
TBmakeVardecs (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeVardecs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_vardecs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_vardecs = MEMmalloc (sizeof (struct SONS_N_VARDECS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_vardecs = MEMmalloc (sizeof (struct ATTRIBS_N_VARDECS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_vardecs;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  VARDECS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  VARDECS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VARDECS_FIRST (this) != NULL)
      && (NODE_TYPE (VARDECS_FIRST (this)) != N_vardec))
    {
      CTIwarn ("Field First of node N_VarDecs has non-allowed target node.");
    }
  if ((VARDECS_NEXT (this) != NULL)
      && (NODE_TYPE (VARDECS_NEXT (this)) != N_vardecs))
    {
      CTIwarn ("Field Next of node N_VarDecs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_VarDec :
 *****************************************************************************/

node *
TBmakeVardec (basictype Type, node * Id, node * Assign)
{
  node *this;
  DBUG_ENTER ("TBmakeVardec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_vardec = MEMmalloc (sizeof (struct SONS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_vardec = MEMmalloc (sizeof (struct ATTRIBS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  VARDEC_ID (this) = Id;
  DBUG_PRINT ("MAKE", ("assigning son Assign initial value: %s ", Assign));
  VARDEC_ASSIGN (this) = Assign;
  VARDEC_TYPE (this) = Type;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VARDEC_ID (this) != NULL) && (NODE_TYPE (VARDEC_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_VarDec has non-allowed target node.");
    }
  if ((VARDEC_ASSIGN (this) != NULL))
    {
      CTIwarn ("Field Assign of node N_VarDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_LocalFunDefs :
 *****************************************************************************/

node *
TBmakeLocalfundefs (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeLocalfundefs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_localfundefs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_localfundefs = MEMmalloc (sizeof (struct SONS_N_LOCALFUNDEFS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_localfundefs =
    MEMmalloc (sizeof (struct ATTRIBS_N_LOCALFUNDEFS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_localfundefs;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  LOCALFUNDEFS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  LOCALFUNDEFS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((LOCALFUNDEFS_FIRST (this) != NULL)
      && (NODE_TYPE (LOCALFUNDEFS_FIRST (this)) != N_fundef))
    {
      CTIwarn
	("Field First of node N_LocalFunDefs has non-allowed target node.");
    }
  if ((LOCALFUNDEFS_NEXT (this) != NULL)
      && (NODE_TYPE (LOCALFUNDEFS_NEXT (this)) != N_localfundefs))
    {
      CTIwarn
	("Field Next of node N_LocalFunDefs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDec :
 *****************************************************************************/

node *
TBmakeGlobaldec (basictype Type, node * Id)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldec = MEMmalloc (sizeof (struct SONS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldec = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldec;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  GLOBALDEC_ID (this) = Id;
  GLOBALDEC_TYPE (this) = Type;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((GLOBALDEC_ID (this) != NULL)
      && (NODE_TYPE (GLOBALDEC_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_GlobalDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDef :
 *****************************************************************************/

node *
TBmakeGlobaldef (basictype Type, bool Export, node * Id, node * Assign)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldef");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldef = MEMmalloc (sizeof (struct SONS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldef = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  GLOBALDEF_ID (this) = Id;
  DBUG_PRINT ("MAKE", ("assigning son Assign initial value: %s ", Assign));
  GLOBALDEF_ASSIGN (this) = Assign;
  GLOBALDEF_TYPE (this) = Type;
  GLOBALDEF_EXPORT (this) = Export;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((GLOBALDEF_ID (this) != NULL)
      && (NODE_TYPE (GLOBALDEF_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_GlobalDef has non-allowed target node.");
    }
  if ((GLOBALDEF_ASSIGN (this) != NULL)
      && (NODE_TYPE (GLOBALDEF_ASSIGN (this)) != N_assign))
    {
      CTIwarn
	("Field Assign of node N_GlobalDef has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Params :
 *****************************************************************************/

node *
TBmakeParams (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeParams");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_params;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_params = MEMmalloc (sizeof (struct SONS_N_PARAMS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_params = MEMmalloc (sizeof (struct ATTRIBS_N_PARAMS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_params;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  PARAMS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  PARAMS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PARAMS_FIRST (this) != NULL)
      && (NODE_TYPE (PARAMS_FIRST (this)) != N_param))
    {
      CTIwarn ("Field First of node N_Params has non-allowed target node.");
    }
  if ((PARAMS_NEXT (this) != NULL)
      && (NODE_TYPE (PARAMS_NEXT (this)) != N_params))
    {
      CTIwarn ("Field Next of node N_Params has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Param :
 *****************************************************************************/

node *
TBmakeParam (basictype Type, node * Id)
{
  node *this;
  DBUG_ENTER ("TBmakeParam");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_param = MEMmalloc (sizeof (struct SONS_N_PARAM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_param = MEMmalloc (sizeof (struct ATTRIBS_N_PARAM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  PARAM_ID (this) = Id;
  PARAM_TYPE (this) = Type;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PARAM_ID (this) != NULL) && (NODE_TYPE (PARAM_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_Param has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Id :
 *****************************************************************************/

node *
TBmakeId ()
{
  node *this;
  DBUG_ENTER ("TBmakeId");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_id;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_id = MEMmalloc (sizeof (struct SONS_N_ID));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_id = MEMmalloc (sizeof (struct ATTRIBS_N_ID));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_id;
  ID_NAME (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Stmts :
 *****************************************************************************/

node *
TBmakeStmts (node * Stmt, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeStmts");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_stmts;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_stmts = MEMmalloc (sizeof (struct SONS_N_STMTS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_stmts = MEMmalloc (sizeof (struct ATTRIBS_N_STMTS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_stmts;
  DBUG_PRINT ("MAKE", ("assigning son Stmt initial value: %s ", Stmt));
  STMTS_STMT (this) = Stmt;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  STMTS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((STMTS_STMT (this) != NULL)
      && (NODE_TYPE (STMTS_STMT (this)) != N_assign)
      && (NODE_TYPE (STMTS_STMT (this)) != N_while)
      && (NODE_TYPE (STMTS_STMT (this)) != N_if)
      && (NODE_TYPE (STMTS_STMT (this)) != N_for)
      && (NODE_TYPE (STMTS_STMT (this)) != N_return)
      && (NODE_TYPE (STMTS_STMT (this)) != N_dowhile))
    {
      CTIwarn ("Field Stmt of node N_Stmts has non-allowed target node.");
    }
  if ((STMTS_NEXT (this) != NULL)
      && (NODE_TYPE (STMTS_NEXT (this)) != N_stmts))
    {
      CTIwarn ("Field Next of node N_Stmts has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Assign :
 *****************************************************************************/

node *
TBmakeAssign (node * Id, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeAssign");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_assign = MEMmalloc (sizeof (struct SONS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_assign = MEMmalloc (sizeof (struct ATTRIBS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  ASSIGN_ID (this) = Id;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  ASSIGN_EXPR (this) = Expr;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ASSIGN_ID (this) != NULL) && (NODE_TYPE (ASSIGN_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_Assign has non-allowed target node.");
    }
  if ((ASSIGN_EXPR (this) != NULL)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_binop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_monop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_cast)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_funcall)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_id)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_const))
    {
      CTIwarn ("Field Expr of node N_Assign has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunCall :
 *****************************************************************************/

node *
TBmakeFuncall (node * Id, node * Exprs)
{
  node *this;
  DBUG_ENTER ("TBmakeFuncall");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funcall = MEMmalloc (sizeof (struct SONS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funcall = MEMmalloc (sizeof (struct ATTRIBS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  FUNCALL_ID (this) = Id;
  DBUG_PRINT ("MAKE", ("assigning son Exprs initial value: %s ", Exprs));
  FUNCALL_EXPRS (this) = Exprs;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNCALL_ID (this) != NULL) && (NODE_TYPE (FUNCALL_ID (this)) != N_id))
    {
      CTIwarn ("Field Id of node N_FunCall has non-allowed target node.");
    }
  if ((FUNCALL_EXPRS (this) != NULL)
      && (NODE_TYPE (FUNCALL_EXPRS (this)) != N_exprs))
    {
      CTIwarn ("Field Exprs of node N_FunCall has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_If :
 *****************************************************************************/

node *
TBmakeIf (node * Expr, node * Block, node * ElseBlock)
{
  node *this;
  DBUG_ENTER ("TBmakeIf");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_if = MEMmalloc (sizeof (struct SONS_N_IF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_if = MEMmalloc (sizeof (struct ATTRIBS_N_IF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  IF_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  IF_BLOCK (this) = Block;
  DBUG_PRINT ("MAKE",
	      ("assigning son ElseBlock initial value: %s ", ElseBlock));
  IF_ELSEBLOCK (this) = ElseBlock;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((IF_EXPR (this) != NULL) && (NODE_TYPE (IF_EXPR (this)) != N_binop)
      && (NODE_TYPE (IF_EXPR (this)) != N_monop)
      && (NODE_TYPE (IF_EXPR (this)) != N_cast)
      && (NODE_TYPE (IF_EXPR (this)) != N_funcall)
      && (NODE_TYPE (IF_EXPR (this)) != N_id)
      && (NODE_TYPE (IF_EXPR (this)) != N_const))
    {
      CTIwarn ("Field Expr of node N_If has non-allowed target node.");
    }
  if ((IF_BLOCK (this) != NULL) && (NODE_TYPE (IF_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_If has non-allowed target node.");
    }
  if ((IF_ELSEBLOCK (this) != NULL)
      && (NODE_TYPE (IF_ELSEBLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field ElseBlock of node N_If has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_While :
 *****************************************************************************/

node *
TBmakeWhile (node * Expr, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeWhile");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_while = MEMmalloc (sizeof (struct SONS_N_WHILE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_while = MEMmalloc (sizeof (struct ATTRIBS_N_WHILE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  WHILE_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  WHILE_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((WHILE_EXPR (this) != NULL)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_binop)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_monop)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_cast)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_funcall)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_id)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_const))
    {
      CTIwarn ("Field Expr of node N_While has non-allowed target node.");
    }
  if ((WHILE_BLOCK (this) != NULL)
      && (NODE_TYPE (WHILE_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_While has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_For :
 *****************************************************************************/

node *
TBmakeFor (node * Assign, node * ExprStop, node * ExprIncr, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeFor");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_for = MEMmalloc (sizeof (struct SONS_N_FOR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_for = MEMmalloc (sizeof (struct ATTRIBS_N_FOR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE", ("assigning son Assign initial value: %s ", Assign));
  FOR_ASSIGN (this) = Assign;
  DBUG_PRINT ("MAKE",
	      ("assigning son ExprStop initial value: %s ", ExprStop));
  FOR_EXPRSTOP (this) = ExprStop;
  DBUG_PRINT ("MAKE",
	      ("assigning son ExprIncr initial value: %s ", ExprIncr));
  FOR_EXPRINCR (this) = ExprIncr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  FOR_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FOR_ASSIGN (this) != NULL)
      && (NODE_TYPE (FOR_ASSIGN (this)) != N_assign))
    {
      CTIwarn ("Field Assign of node N_For has non-allowed target node.");
    }
  if ((FOR_EXPRSTOP (this) != NULL)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_expr))
    {
      CTIwarn ("Field ExprStop of node N_For has non-allowed target node.");
    }
  if ((FOR_EXPRINCR (this) != NULL)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_expr))
    {
      CTIwarn ("Field ExprIncr of node N_For has non-allowed target node.");
    }
  if ((FOR_BLOCK (this) != NULL) && (NODE_TYPE (FOR_BLOCK (this)) != N_stmts))
    {
      CTIwarn ("Field Block of node N_For has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Return :
 *****************************************************************************/

node *
TBmakeReturn (node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeReturn");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_return = MEMmalloc (sizeof (struct SONS_N_RETURN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_return = MEMmalloc (sizeof (struct ATTRIBS_N_RETURN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  RETURN_EXPR (this) = Expr;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((RETURN_EXPR (this) != NULL)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_binop)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_monop)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_cast)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_funcall)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_id)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_const))
    {
      CTIwarn ("Field Expr of node N_Return has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Exprs :
 *****************************************************************************/

node *
TBmakeExprs (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeExprs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_exprs = MEMmalloc (sizeof (struct SONS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_exprs = MEMmalloc (sizeof (struct ATTRIBS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  EXPRS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  EXPRS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((EXPRS_FIRST (this) != NULL)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_binop)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_monop)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_cast)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_funcall)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_id)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_const))
    {
      CTIwarn ("Field First of node N_Exprs has non-allowed target node.");
    }
  if ((EXPRS_NEXT (this) != NULL)
      && (NODE_TYPE (EXPRS_NEXT (this)) != N_exprs))
    {
      CTIwarn ("Field Next of node N_Exprs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_BinOp :
 *****************************************************************************/

node *
TBmakeBinop (binop Op, node * Left, node * Right)
{
  node *this;
  DBUG_ENTER ("TBmakeBinop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_binop = MEMmalloc (sizeof (struct SONS_N_BINOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_binop = MEMmalloc (sizeof (struct ATTRIBS_N_BINOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("assigning son Left initial value: %s ", Left));
  BINOP_LEFT (this) = Left;
  DBUG_PRINT ("MAKE", ("assigning son Right initial value: %s ", Right));
  BINOP_RIGHT (this) = Right;
  BINOP_OP (this) = Op;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((BINOP_LEFT (this) != NULL)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_binop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_monop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_cast)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_id)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_const))
    {
      CTIwarn ("Field Left of node N_BinOp has non-allowed target node.");
    }
  if ((BINOP_RIGHT (this) != NULL)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_binop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_monop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_cast)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_id)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_const))
    {
      CTIwarn ("Field Right of node N_BinOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_MonOp :
 *****************************************************************************/

node *
TBmakeMonop (Op, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeMonop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_monop = MEMmalloc (sizeof (struct SONS_N_MONOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_monop = MEMmalloc (sizeof (struct ATTRIBS_N_MONOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  MONOP_EXPR (this) = Expr;
  MONOP_OP (this) = Op;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((MONOP_EXPR (this) != NULL)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_expr))
    {
      CTIwarn ("Field Expr of node N_MonOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Cast :
 *****************************************************************************/

node *
TBmakeCast (basictype CastType, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeCast");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_cast = MEMmalloc (sizeof (struct SONS_N_CAST));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_cast = MEMmalloc (sizeof (struct ATTRIBS_N_CAST));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  CAST_EXPR (this) = Expr;
  CAST_CASTTYPE (this) = CastType;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((CAST_EXPR (this) != NULL) && (NODE_TYPE (CAST_EXPR (this)) != N_expr))
    {
      CTIwarn ("Field Expr of node N_Cast has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Num :
 *****************************************************************************/

node *
TBmakeNum (int Value)
{
  node *this;
  DBUG_ENTER ("TBmakeNum");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_num;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_num = MEMmalloc (sizeof (struct SONS_N_NUM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_num = MEMmalloc (sizeof (struct ATTRIBS_N_NUM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_num;
  NUM_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Float :
 *****************************************************************************/

node *
TBmakeFloat ()
{
  node *this;
  DBUG_ENTER ("TBmakeFloat");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_float;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_float = MEMmalloc (sizeof (struct SONS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_float = MEMmalloc (sizeof (struct ATTRIBS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_float;
  FLOAT_VALUE (this) = 0.0;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Bool :
 *****************************************************************************/

node *
TBmakeBool (bool Value)
{
  node *this;
  DBUG_ENTER ("TBmakeBool");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_bool;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_bool = MEMmalloc (sizeof (struct SONS_N_BOOL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_bool = MEMmalloc (sizeof (struct ATTRIBS_N_BOOL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_bool;
  BOOL_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Error :
 *****************************************************************************/

node *
TBmakeError (char *message, compiler_phase_t anyphase, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeError");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_error = MEMmalloc (sizeof (struct SONS_N_ERROR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_error = MEMmalloc (sizeof (struct ATTRIBS_N_ERROR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  ERROR_NEXT (this) = Next;
  ERROR_MESSAGE (this) = message;
  ERROR_ANYPHASE (this) = anyphase;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ERROR_NEXT (this) != NULL)
      && (NODE_TYPE (ERROR_NEXT (this)) != N_error))
    {
      CTIwarn ("Field Next of node N_Error has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

  /* end of file */
