
/**
 * @file node_basic.c
 *
 * Functions to allocate node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: node_basic.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "node_basic.h"
#include "tree_basic.h"
#include "memory.h"
#include "dbug.h"
#include "globals.h"
#include "ctinfo.h"

static node *
MakeEmptyNode ()
{
  node *result;

  DBUG_ENTER ("MakeEmptyNode");

  result = (node *) MEMmalloc (sizeof (node));

  NODE_LINE (result) = global.line;
  NODE_COL (result) = global.col;

  DBUG_RETURN (result);
}



/*****************************************************************************
 * N_Program :
 *****************************************************************************/

node *
TBmakeProgram (node * Declarations, node * SymbolTable)
{
  node *this;
  DBUG_ENTER ("TBmakeProgram");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_program;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_program = MEMmalloc (sizeof (struct SONS_N_PROGRAM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_program = MEMmalloc (sizeof (struct ATTRIBS_N_PROGRAM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_program;
  DBUG_PRINT ("MAKE",
	      ("assigning son Declarations initial value: %s ",
	       Declarations));
  PROGRAM_DECLARATIONS (this) = Declarations;
  DBUG_PRINT ("MAKE",
	      ("assigning son SymbolTable initial value: %s ", SymbolTable));
  PROGRAM_SYMBOLTABLE (this) = SymbolTable;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PROGRAM_DECLARATIONS (this) != NULL)
      && (NODE_TYPE (PROGRAM_DECLARATIONS (this)) != N_declarations))
    {
      CTIwarn
	("Field Declarations of node N_Program has non-allowed target node.");
    }
  if ((PROGRAM_SYMBOLTABLE (this) != NULL)
      && (NODE_TYPE (PROGRAM_SYMBOLTABLE (this)) != N_symboltable))
    {
      CTIwarn
	("Field SymbolTable of node N_Program has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Declarations :
 *****************************************************************************/

node *
TBmakeDeclarations (node * Declaration, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeDeclarations");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_declarations = MEMmalloc (sizeof (struct SONS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_declarations =
    MEMmalloc (sizeof (struct ATTRIBS_N_DECLARATIONS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_declarations;
  DBUG_PRINT ("MAKE",
	      ("assigning son Declaration initial value: %s ", Declaration));
  DECLARATIONS_DECLARATION (this) = Declaration;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  DECLARATIONS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((DECLARATIONS_DECLARATION (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_fundefdec)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_globaldec)
      && (NODE_TYPE (DECLARATIONS_DECLARATION (this)) != N_globaldef))
    {
      CTIwarn
	("Field Declaration of node N_Declarations has non-allowed target node.");
    }
  if ((DECLARATIONS_NEXT (this) != NULL)
      && (NODE_TYPE (DECLARATIONS_NEXT (this)) != N_declarations))
    {
      CTIwarn
	("Field Next of node N_Declarations has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunDefDec :
 *****************************************************************************/

node *
TBmakeFundefdec (bool Export, basictype RetType, char *Id, node * Param,
		 node * Body, node * SymbolTable)
{
  node *this;
  DBUG_ENTER ("TBmakeFundefdec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_fundefdec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_fundefdec = MEMmalloc (sizeof (struct SONS_N_FUNDEFDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_fundefdec = MEMmalloc (sizeof (struct ATTRIBS_N_FUNDEFDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_fundefdec;
  DBUG_PRINT ("MAKE", ("assigning son Param initial value: %s ", Param));
  FUNDEFDEC_PARAM (this) = Param;
  DBUG_PRINT ("MAKE", ("assigning son Body initial value: %s ", Body));
  FUNDEFDEC_BODY (this) = Body;
  DBUG_PRINT ("MAKE",
	      ("assigning son SymbolTable initial value: %s ", SymbolTable));
  FUNDEFDEC_SYMBOLTABLE (this) = SymbolTable;
  FUNDEFDEC_EXPORT (this) = Export;
  FUNDEFDEC_RETTYPE (this) = RetType;
  FUNDEFDEC_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNDEFDEC_PARAM (this) != NULL)
      && (NODE_TYPE (FUNDEFDEC_PARAM (this)) != N_param))
    {
      CTIwarn
	("Field Param of node N_FunDefDec has non-allowed target node.");
    }
  if ((FUNDEFDEC_BODY (this) != NULL)
      && (NODE_TYPE (FUNDEFDEC_BODY (this)) != N_funbody))
    {
      CTIwarn ("Field Body of node N_FunDefDec has non-allowed target node.");
    }
  if ((FUNDEFDEC_SYMBOLTABLE (this) != NULL)
      && (NODE_TYPE (FUNDEFDEC_SYMBOLTABLE (this)) != N_symboltable))
    {
      CTIwarn
	("Field SymbolTable of node N_FunDefDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunBody :
 *****************************************************************************/

node *
TBmakeFunbody (node * VarDec, node * LocalFunDefs, node * Statements)
{
  node *this;
  DBUG_ENTER ("TBmakeFunbody");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funbody = MEMmalloc (sizeof (struct SONS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funbody = MEMmalloc (sizeof (struct ATTRIBS_N_FUNBODY));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funbody;
  DBUG_PRINT ("MAKE", ("assigning son VarDec initial value: %s ", VarDec));
  FUNBODY_VARDEC (this) = VarDec;
  DBUG_PRINT ("MAKE",
	      ("assigning son LocalFunDefs initial value: %s ",
	       LocalFunDefs));
  FUNBODY_LOCALFUNDEFS (this) = LocalFunDefs;
  DBUG_PRINT ("MAKE",
	      ("assigning son Statements initial value: %s ", Statements));
  FUNBODY_STATEMENTS (this) = Statements;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNBODY_VARDEC (this) != NULL)
      && (NODE_TYPE (FUNBODY_VARDEC (this)) != N_vardec))
    {
      CTIwarn ("Field VarDec of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_LOCALFUNDEFS (this) != NULL)
      && (NODE_TYPE (FUNBODY_LOCALFUNDEFS (this)) != N_localfundefs))
    {
      CTIwarn
	("Field LocalFunDefs of node N_FunBody has non-allowed target node.");
    }
  if ((FUNBODY_STATEMENTS (this) != NULL)
      && (NODE_TYPE (FUNBODY_STATEMENTS (this)) != N_statements))
    {
      CTIwarn
	("Field Statements of node N_FunBody has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_VarDec :
 *****************************************************************************/

node *
TBmakeVardec (basictype Type, char *Id, node * Expr, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeVardec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_vardec = MEMmalloc (sizeof (struct SONS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_vardec = MEMmalloc (sizeof (struct ATTRIBS_N_VARDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_vardec;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  VARDEC_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  VARDEC_NEXT (this) = Next;
  VARDEC_TYPE (this) = Type;
  VARDEC_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((VARDEC_EXPR (this) != NULL)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_binop)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_monop)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_cast)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_funcall)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_var)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_num)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_float)
      && (NODE_TYPE (VARDEC_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_VarDec has non-allowed target node.");
    }
  if ((VARDEC_NEXT (this) != NULL)
      && (NODE_TYPE (VARDEC_NEXT (this)) != N_vardec))
    {
      CTIwarn ("Field Next of node N_VarDec has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_LocalFunDefs :
 *****************************************************************************/

node *
TBmakeLocalfundefs (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeLocalfundefs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_localfundefs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_localfundefs = MEMmalloc (sizeof (struct SONS_N_LOCALFUNDEFS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_localfundefs =
    MEMmalloc (sizeof (struct ATTRIBS_N_LOCALFUNDEFS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_localfundefs;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  LOCALFUNDEFS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  LOCALFUNDEFS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((LOCALFUNDEFS_FIRST (this) != NULL)
      && (NODE_TYPE (LOCALFUNDEFS_FIRST (this)) != N_fundefdec))
    {
      CTIwarn
	("Field First of node N_LocalFunDefs has non-allowed target node.");
    }
  if ((LOCALFUNDEFS_NEXT (this) != NULL)
      && (NODE_TYPE (LOCALFUNDEFS_NEXT (this)) != N_localfundefs))
    {
      CTIwarn
	("Field Next of node N_LocalFunDefs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDec :
 *****************************************************************************/

node *
TBmakeGlobaldec (basictype Type, char *Id)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldec");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldec;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldec = MEMmalloc (sizeof (struct SONS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldec = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEC));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldec;
  GLOBALDEC_TYPE (this) = Type;
  GLOBALDEC_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_GlobalDef :
 *****************************************************************************/

node *
TBmakeGlobaldef (basictype Type, bool Export, char *Id, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeGlobaldef");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_globaldef = MEMmalloc (sizeof (struct SONS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_globaldef = MEMmalloc (sizeof (struct ATTRIBS_N_GLOBALDEF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_globaldef;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  GLOBALDEF_EXPR (this) = Expr;
  GLOBALDEF_TYPE (this) = Type;
  GLOBALDEF_EXPORT (this) = Export;
  GLOBALDEF_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((GLOBALDEF_EXPR (this) != NULL)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_binop)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_monop)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_cast)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_funcall)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_var)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_num)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_float)
      && (NODE_TYPE (GLOBALDEF_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_GlobalDef has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Param :
 *****************************************************************************/

node *
TBmakeParam (basictype Type, node * Id, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeParam");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_param = MEMmalloc (sizeof (struct SONS_N_PARAM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_param = MEMmalloc (sizeof (struct ATTRIBS_N_PARAM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_param;
  DBUG_PRINT ("MAKE", ("assigning son Id initial value: %s ", Id));
  PARAM_ID (this) = Id;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  PARAM_NEXT (this) = Next;
  PARAM_TYPE (this) = Type;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((PARAM_ID (this) != NULL) && (NODE_TYPE (PARAM_ID (this)) != N_var))
    {
      CTIwarn ("Field Id of node N_Param has non-allowed target node.");
    }
  if ((PARAM_NEXT (this) != NULL)
      && (NODE_TYPE (PARAM_NEXT (this)) != N_param))
    {
      CTIwarn ("Field Next of node N_Param has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Var :
 *****************************************************************************/

node *
TBmakeVar (char *Name)
{
  node *this;
  DBUG_ENTER ("TBmakeVar");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_var;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_var = MEMmalloc (sizeof (struct SONS_N_VAR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_var = MEMmalloc (sizeof (struct ATTRIBS_N_VAR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_var;
  VAR_NAME (this) = Name;
  VAR_LINK (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Statements :
 *****************************************************************************/

node *
TBmakeStatements (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeStatements");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_statements;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_statements = MEMmalloc (sizeof (struct SONS_N_STATEMENTS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_statements =
    MEMmalloc (sizeof (struct ATTRIBS_N_STATEMENTS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_statements;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  STATEMENTS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  STATEMENTS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((STATEMENTS_FIRST (this) != NULL)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_assign)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_funcall)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_while)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_dowhile)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_if)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_for)
      && (NODE_TYPE (STATEMENTS_FIRST (this)) != N_return))
    {
      CTIwarn
	("Field First of node N_Statements has non-allowed target node.");
    }
  if ((STATEMENTS_NEXT (this) != NULL)
      && (NODE_TYPE (STATEMENTS_NEXT (this)) != N_statements))
    {
      CTIwarn
	("Field Next of node N_Statements has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Assign :
 *****************************************************************************/

node *
TBmakeAssign (char *Id, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeAssign");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_assign = MEMmalloc (sizeof (struct SONS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_assign = MEMmalloc (sizeof (struct ATTRIBS_N_ASSIGN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_assign;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  ASSIGN_EXPR (this) = Expr;
  ASSIGN_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ASSIGN_EXPR (this) != NULL)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_binop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_monop)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_cast)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_funcall)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_var)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_num)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_float)
      && (NODE_TYPE (ASSIGN_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_Assign has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_FunCall :
 *****************************************************************************/

node *
TBmakeFuncall (char *Id, node * Exprs)
{
  node *this;
  DBUG_ENTER ("TBmakeFuncall");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_funcall = MEMmalloc (sizeof (struct SONS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_funcall = MEMmalloc (sizeof (struct ATTRIBS_N_FUNCALL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_funcall;
  DBUG_PRINT ("MAKE", ("assigning son Exprs initial value: %s ", Exprs));
  FUNCALL_EXPRS (this) = Exprs;
  FUNCALL_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FUNCALL_EXPRS (this) != NULL)
      && (NODE_TYPE (FUNCALL_EXPRS (this)) != N_exprs))
    {
      CTIwarn ("Field Exprs of node N_FunCall has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_If :
 *****************************************************************************/

node *
TBmakeIf (node * Expr, node * Block, node * ElseBlock)
{
  node *this;
  DBUG_ENTER ("TBmakeIf");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_if = MEMmalloc (sizeof (struct SONS_N_IF));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_if = MEMmalloc (sizeof (struct ATTRIBS_N_IF));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_if;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  IF_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  IF_BLOCK (this) = Block;
  DBUG_PRINT ("MAKE",
	      ("assigning son ElseBlock initial value: %s ", ElseBlock));
  IF_ELSEBLOCK (this) = ElseBlock;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((IF_EXPR (this) != NULL) && (NODE_TYPE (IF_EXPR (this)) != N_binop)
      && (NODE_TYPE (IF_EXPR (this)) != N_monop)
      && (NODE_TYPE (IF_EXPR (this)) != N_cast)
      && (NODE_TYPE (IF_EXPR (this)) != N_funcall)
      && (NODE_TYPE (IF_EXPR (this)) != N_var)
      && (NODE_TYPE (IF_EXPR (this)) != N_num)
      && (NODE_TYPE (IF_EXPR (this)) != N_float)
      && (NODE_TYPE (IF_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_If has non-allowed target node.");
    }
  if ((IF_BLOCK (this) != NULL)
      && (NODE_TYPE (IF_BLOCK (this)) != N_statements))
    {
      CTIwarn ("Field Block of node N_If has non-allowed target node.");
    }
  if ((IF_ELSEBLOCK (this) != NULL)
      && (NODE_TYPE (IF_ELSEBLOCK (this)) != N_statements))
    {
      CTIwarn ("Field ElseBlock of node N_If has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_While :
 *****************************************************************************/

node *
TBmakeWhile (node * Expr, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeWhile");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_while = MEMmalloc (sizeof (struct SONS_N_WHILE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_while = MEMmalloc (sizeof (struct ATTRIBS_N_WHILE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_while;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  WHILE_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  WHILE_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((WHILE_EXPR (this) != NULL)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_binop)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_monop)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_cast)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_funcall)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_var)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_num)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_float)
      && (NODE_TYPE (WHILE_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_While has non-allowed target node.");
    }
  if ((WHILE_BLOCK (this) != NULL)
      && (NODE_TYPE (WHILE_BLOCK (this)) != N_statements))
    {
      CTIwarn ("Field Block of node N_While has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_DoWhile :
 *****************************************************************************/

node *
TBmakeDowhile (node * Expr, node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeDowhile");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_dowhile;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_dowhile = MEMmalloc (sizeof (struct SONS_N_DOWHILE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_dowhile = MEMmalloc (sizeof (struct ATTRIBS_N_DOWHILE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_dowhile;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  DOWHILE_EXPR (this) = Expr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  DOWHILE_BLOCK (this) = Block;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((DOWHILE_EXPR (this) != NULL)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_binop)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_monop)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_cast)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_funcall)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_var)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_num)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_float)
      && (NODE_TYPE (DOWHILE_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_DoWhile has non-allowed target node.");
    }
  if ((DOWHILE_BLOCK (this) != NULL)
      && (NODE_TYPE (DOWHILE_BLOCK (this)) != N_statements))
    {
      CTIwarn ("Field Block of node N_DoWhile has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_For :
 *****************************************************************************/

node *
TBmakeFor (char *Id, node * ExprStart, node * ExprStop, node * ExprIncr,
	   node * Block)
{
  node *this;
  DBUG_ENTER ("TBmakeFor");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_for = MEMmalloc (sizeof (struct SONS_N_FOR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_for = MEMmalloc (sizeof (struct ATTRIBS_N_FOR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_for;
  DBUG_PRINT ("MAKE",
	      ("assigning son ExprStart initial value: %s ", ExprStart));
  FOR_EXPRSTART (this) = ExprStart;
  DBUG_PRINT ("MAKE",
	      ("assigning son ExprStop initial value: %s ", ExprStop));
  FOR_EXPRSTOP (this) = ExprStop;
  DBUG_PRINT ("MAKE",
	      ("assigning son ExprIncr initial value: %s ", ExprIncr));
  FOR_EXPRINCR (this) = ExprIncr;
  DBUG_PRINT ("MAKE", ("assigning son Block initial value: %s ", Block));
  FOR_BLOCK (this) = Block;
  FOR_ID (this) = Id;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((FOR_EXPRSTART (this) != NULL)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_binop)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_monop)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_cast)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_funcall)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_var)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_num)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_float)
      && (NODE_TYPE (FOR_EXPRSTART (this)) != N_bool))
    {
      CTIwarn ("Field ExprStart of node N_For has non-allowed target node.");
    }
  if ((FOR_EXPRSTOP (this) != NULL)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_binop)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_monop)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_cast)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_funcall)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_var)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_num)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_float)
      && (NODE_TYPE (FOR_EXPRSTOP (this)) != N_bool))
    {
      CTIwarn ("Field ExprStop of node N_For has non-allowed target node.");
    }
  if ((FOR_EXPRINCR (this) != NULL)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_binop)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_monop)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_cast)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_funcall)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_var)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_num)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_float)
      && (NODE_TYPE (FOR_EXPRINCR (this)) != N_bool))
    {
      CTIwarn ("Field ExprIncr of node N_For has non-allowed target node.");
    }
  if ((FOR_BLOCK (this) != NULL)
      && (NODE_TYPE (FOR_BLOCK (this)) != N_statements))
    {
      CTIwarn ("Field Block of node N_For has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Return :
 *****************************************************************************/

node *
TBmakeReturn (node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeReturn");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_return = MEMmalloc (sizeof (struct SONS_N_RETURN));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_return = MEMmalloc (sizeof (struct ATTRIBS_N_RETURN));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_return;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  RETURN_EXPR (this) = Expr;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((RETURN_EXPR (this) != NULL)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_binop)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_monop)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_cast)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_funcall)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_var)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_num)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_float)
      && (NODE_TYPE (RETURN_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_Return has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Exprs :
 *****************************************************************************/

node *
TBmakeExprs (node * First, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeExprs");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_exprs = MEMmalloc (sizeof (struct SONS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_exprs = MEMmalloc (sizeof (struct ATTRIBS_N_EXPRS));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_exprs;
  DBUG_PRINT ("MAKE", ("assigning son First initial value: %s ", First));
  EXPRS_FIRST (this) = First;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  EXPRS_NEXT (this) = Next;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((EXPRS_FIRST (this) != NULL)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_binop)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_monop)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_cast)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_funcall)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_var)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_num)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_float)
      && (NODE_TYPE (EXPRS_FIRST (this)) != N_bool))
    {
      CTIwarn ("Field First of node N_Exprs has non-allowed target node.");
    }
  if ((EXPRS_NEXT (this) != NULL)
      && (NODE_TYPE (EXPRS_NEXT (this)) != N_exprs))
    {
      CTIwarn ("Field Next of node N_Exprs has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_BinOp :
 *****************************************************************************/

node *
TBmakeBinop (binop Op, node * Left, node * Right)
{
  node *this;
  DBUG_ENTER ("TBmakeBinop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_binop = MEMmalloc (sizeof (struct SONS_N_BINOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_binop = MEMmalloc (sizeof (struct ATTRIBS_N_BINOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_binop;
  DBUG_PRINT ("MAKE", ("assigning son Left initial value: %s ", Left));
  BINOP_LEFT (this) = Left;
  DBUG_PRINT ("MAKE", ("assigning son Right initial value: %s ", Right));
  BINOP_RIGHT (this) = Right;
  BINOP_OP (this) = Op;
  BINOP_EXPRESSIONTYPE (this) = BT_unknown;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((BINOP_LEFT (this) != NULL)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_binop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_monop)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_cast)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_var)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_num)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_float)
      && (NODE_TYPE (BINOP_LEFT (this)) != N_bool))
    {
      CTIwarn ("Field Left of node N_BinOp has non-allowed target node.");
    }
  if ((BINOP_RIGHT (this) != NULL)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_binop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_monop)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_cast)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_funcall)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_var)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_num)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_float)
      && (NODE_TYPE (BINOP_RIGHT (this)) != N_bool))
    {
      CTIwarn ("Field Right of node N_BinOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_MonOp :
 *****************************************************************************/

node *
TBmakeMonop (monop Op, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeMonop");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_monop = MEMmalloc (sizeof (struct SONS_N_MONOP));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_monop = MEMmalloc (sizeof (struct ATTRIBS_N_MONOP));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_monop;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  MONOP_EXPR (this) = Expr;
  MONOP_OP (this) = Op;
  MONOP_EXPRESSIONTYPE (this) = BT_unknown;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((MONOP_EXPR (this) != NULL)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_binop)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_monop)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_cast)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_funcall)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_var)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_num)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_float)
      && (NODE_TYPE (MONOP_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_MonOp has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Cast :
 *****************************************************************************/

node *
TBmakeCast (basictype CastType, node * Expr)
{
  node *this;
  DBUG_ENTER ("TBmakeCast");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_cast = MEMmalloc (sizeof (struct SONS_N_CAST));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_cast = MEMmalloc (sizeof (struct ATTRIBS_N_CAST));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_cast;
  DBUG_PRINT ("MAKE", ("assigning son Expr initial value: %s ", Expr));
  CAST_EXPR (this) = Expr;
  CAST_CASTTYPE (this) = CastType;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((CAST_EXPR (this) != NULL) && (NODE_TYPE (CAST_EXPR (this)) != N_binop)
      && (NODE_TYPE (CAST_EXPR (this)) != N_monop)
      && (NODE_TYPE (CAST_EXPR (this)) != N_cast)
      && (NODE_TYPE (CAST_EXPR (this)) != N_funcall)
      && (NODE_TYPE (CAST_EXPR (this)) != N_var)
      && (NODE_TYPE (CAST_EXPR (this)) != N_num)
      && (NODE_TYPE (CAST_EXPR (this)) != N_float)
      && (NODE_TYPE (CAST_EXPR (this)) != N_bool))
    {
      CTIwarn ("Field Expr of node N_Cast has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Num :
 *****************************************************************************/

node *
TBmakeNum (int Value)
{
  node *this;
  DBUG_ENTER ("TBmakeNum");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_num;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_num = MEMmalloc (sizeof (struct SONS_N_NUM));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_num = MEMmalloc (sizeof (struct ATTRIBS_N_NUM));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_num;
  NUM_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Float :
 *****************************************************************************/

node *
TBmakeFloat (float Value)
{
  node *this;
  DBUG_ENTER ("TBmakeFloat");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_float;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_float = MEMmalloc (sizeof (struct SONS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_float = MEMmalloc (sizeof (struct ATTRIBS_N_FLOAT));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_float;
  FLOAT_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Bool :
 *****************************************************************************/

node *
TBmakeBool (bool Value)
{
  node *this;
  DBUG_ENTER ("TBmakeBool");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_bool;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_bool = MEMmalloc (sizeof (struct SONS_N_BOOL));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_bool = MEMmalloc (sizeof (struct ATTRIBS_N_BOOL));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_bool;
  BOOL_VALUE (this) = Value;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_SymbolTable :
 *****************************************************************************/

node *
TBmakeSymboltable (node * Head)
{
  node *this;
  DBUG_ENTER ("TBmakeSymboltable");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_symboltable;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_symboltable = MEMmalloc (sizeof (struct SONS_N_SYMBOLTABLE));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_symboltable =
    MEMmalloc (sizeof (struct ATTRIBS_N_SYMBOLTABLE));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_symboltable;
  DBUG_PRINT ("MAKE", ("assigning son Head initial value: %s ", Head));
  SYMBOLTABLE_HEAD (this) = Head;
  SYMBOLTABLE_PARENT (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((SYMBOLTABLE_HEAD (this) != NULL)
      && (NODE_TYPE (SYMBOLTABLE_HEAD (this)) != N_symboltableentry))
    {
      CTIwarn
	("Field Head of node N_SymbolTable has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_SymbolTableEntry :
 *****************************************************************************/

node *
TBmakeSymboltableentry (char *Name, basictype Type, bool Function,
			node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeSymboltableentry");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_symboltableentry;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_symboltableentry =
    MEMmalloc (sizeof (struct SONS_N_SYMBOLTABLEENTRY));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_symboltableentry =
    MEMmalloc (sizeof (struct ATTRIBS_N_SYMBOLTABLEENTRY));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_symboltableentry;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  SYMBOLTABLEENTRY_NEXT (this) = Next;
  SYMBOLTABLEENTRY_NAME (this) = Name;
  SYMBOLTABLEENTRY_TYPE (this) = Type;
  SYMBOLTABLEENTRY_FUNCTION (this) = Function;
  SYMBOLTABLEENTRY_PARAMS (this) = NULL;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((SYMBOLTABLEENTRY_NEXT (this) != NULL)
      && (NODE_TYPE (SYMBOLTABLEENTRY_NEXT (this)) != N_symboltableentry))
    {
      CTIwarn
	("Field Next of node N_SymbolTableEntry has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

/*****************************************************************************
 * N_Error :
 *****************************************************************************/

node *
TBmakeError (char *message, compiler_phase_t anyphase, node * Next)
{
  node *this;
  DBUG_ENTER ("TBmakeError");
  DBUG_PRINT ("MAKE", ("allocating node structure"));
  this = MakeEmptyNode ();
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("address: %s ", this));
  DBUG_PRINT ("MAKE", ("allocating sons structure"));
  this->sons.N_error = MEMmalloc (sizeof (struct SONS_N_ERROR));
  DBUG_PRINT ("MAKE", ("allocating attrib structure"));
  this->attribs.N_error = MEMmalloc (sizeof (struct ATTRIBS_N_ERROR));
  DBUG_PRINT ("MAKE", ("setting node type"));
  NODE_TYPE (this) = N_error;
  DBUG_PRINT ("MAKE", ("assigning son Next initial value: %s ", Next));
  ERROR_NEXT (this) = Next;
  ERROR_MESSAGE (this) = message;
  ERROR_ANYPHASE (this) = anyphase;
#ifndef DBUG_OFF
  DBUG_PRINT ("MAKE", ("doing son target checks"));
  if ((ERROR_NEXT (this) != NULL)
      && (NODE_TYPE (ERROR_NEXT (this)) != N_error))
    {
      CTIwarn ("Field Next of node N_Error has non-allowed target node.");
    }
#endif /* DBUG_OFF */
  DBUG_RETURN (this);
}

  /* end of file */
