
/**
 * @file sons.h
 *
 * Defines the NodesUnion and node structures.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: sons.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_SONS_H_
#define _SAC_SONS_H_

#include "types.h"


/******************************************************************************
 * For each node a structure of its sons is defined, named 
 * SONS_<nodename>
 *****************************************************************************/
struct SONS_N_ASSIGN
{
  node *Id;
  node *Expr;
};
struct SONS_N_BINOP
{
  node *Left;
  node *Right;
};
struct SONS_N_BOOL
{
};
struct SONS_N_CAST
{
  node *Expr;
};
struct SONS_N_DECLARATIONS
{
  node *Declaration;
  node *Next;
};
struct SONS_N_DOWHILE
{
  node *Expr;
  node *Block;
};
struct SONS_N_ERROR
{
  node *Next;
};
struct SONS_N_EXPRS
{
  node *First;
  node *Next;
};
struct SONS_N_FLOAT
{
};
struct SONS_N_FOR
{
  node *Id;
  node *ExprStart;
  node *ExprStop;
  node *ExprIncr;
  node *Block;
};
struct SONS_N_FUNBODY
{
  node *VarDec;
  node *LocalFunDefs;
  node *Statements;
};
struct SONS_N_FUNCALL
{
  node *Id;
  node *Exprs;
};
struct SONS_N_FUNDEFDEC
{
  node *Param;
  node *Body;
};
struct SONS_N_GLOBALDEC
{
};
struct SONS_N_GLOBALDEF
{
  node *Expr;
};
struct SONS_N_ID
{
};
struct SONS_N_IF
{
  node *Expr;
  node *Block;
  node *ElseBlock;
};
struct SONS_N_LOCALFUNDEFS
{
  node *First;
  node *Next;
};
struct SONS_N_MONOP
{
  node *Expr;
};
struct SONS_N_NUM
{
};
struct SONS_N_PARAM
{
  node *Next;
};
struct SONS_N_RETURN
{
  node *Expr;
};
struct SONS_N_STEFUNTYPE
{
  node *Next;
};
struct SONS_N_STMTS
{
  node *First;
  node *Next;
};
struct SONS_N_SYMBOLTABLE
{
  node *Head;
};
struct SONS_N_SYMBOLTABLEENTRY
{
  node *Next;
  node *FunTypes;
};
struct SONS_N_VARDEC
{
  node *Expr;
  node *Next;
};
struct SONS_N_WHILE
{
  node *Expr;
  node *Block;
};
/*****************************************************************************
 * This union handles all different types of sons. Its members are
 * called N_nodename.
 ****************************************************************************/
struct SONUNION
{
  struct SONS_N_ASSIGN *N_assign;
  struct SONS_N_BINOP *N_binop;
  struct SONS_N_BOOL *N_bool;
  struct SONS_N_CAST *N_cast;
  struct SONS_N_DECLARATIONS *N_declarations;
  struct SONS_N_DOWHILE *N_dowhile;
  struct SONS_N_ERROR *N_error;
  struct SONS_N_EXPRS *N_exprs;
  struct SONS_N_FLOAT *N_float;
  struct SONS_N_FOR *N_for;
  struct SONS_N_FUNBODY *N_funbody;
  struct SONS_N_FUNCALL *N_funcall;
  struct SONS_N_FUNDEFDEC *N_fundefdec;
  struct SONS_N_GLOBALDEC *N_globaldec;
  struct SONS_N_GLOBALDEF *N_globaldef;
  struct SONS_N_ID *N_id;
  struct SONS_N_IF *N_if;
  struct SONS_N_LOCALFUNDEFS *N_localfundefs;
  struct SONS_N_MONOP *N_monop;
  struct SONS_N_NUM *N_num;
  struct SONS_N_PARAM *N_param;
  struct SONS_N_RETURN *N_return;
  struct SONS_N_STEFUNTYPE *N_stefuntype;
  struct SONS_N_STMTS *N_stmts;
  struct SONS_N_SYMBOLTABLE *N_symboltable;
  struct SONS_N_SYMBOLTABLEENTRY *N_symboltableentry;
  struct SONS_N_VARDEC *N_vardec;
  struct SONS_N_WHILE *N_while;
};
#endif /* _SAC_SONS_H_ */
