
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "make_st.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTdeclarations, &PRTfundefdec, &PRTfunbody, &PRTvardec,
     &PRTlocalfundefs, &PRTglobaldec, &PRTglobaldef, &PRTparam, &PRTid,
     &PRTstmts, &PRTassign, &PRTfuncall, &PRTif, &PRTwhile, &PRTdowhile,
     &PRTfor, &PRTreturn, &PRTexprs, &PRTbinop, &PRTmonop, &PRTcast, &PRTnum,
     &PRTfloat, &PRTbool, &PRTsymboltable, &PRTsymboltableentry, &PRTerror}

  /* TR_copy */
  , {&TRAVerror, &COPYdeclarations, &COPYfundefdec, &COPYfunbody, &COPYvardec,
     &COPYlocalfundefs, &COPYglobaldec, &COPYglobaldef, &COPYparam, &COPYid,
     &COPYstmts, &COPYassign, &COPYfuncall, &COPYif, &COPYwhile, &COPYdowhile,
     &COPYfor, &COPYreturn, &COPYexprs, &COPYbinop, &COPYmonop, &COPYcast,
     &COPYnum, &COPYfloat, &COPYbool, &COPYsymboltable, &COPYsymboltableentry,
     &COPYerror}

  /* TR_free */
  , {&TRAVerror, &FREEdeclarations, &FREEfundefdec, &FREEfunbody, &FREEvardec,
     &FREElocalfundefs, &FREEglobaldec, &FREEglobaldef, &FREEparam, &FREEid,
     &FREEstmts, &FREEassign, &FREEfuncall, &FREEif, &FREEwhile, &FREEdowhile,
     &FREEfor, &FREEreturn, &FREEexprs, &FREEbinop, &FREEmonop, &FREEcast,
     &FREEnum, &FREEfloat, &FREEbool, &FREEsymboltable, &FREEsymboltableentry,
     &FREEerror}

  /* TR_chk */
  , {&TRAVerror, &CHKdeclarations, &CHKfundefdec, &CHKfunbody, &CHKvardec,
     &CHKlocalfundefs, &CHKglobaldec, &CHKglobaldef, &CHKparam, &CHKid,
     &CHKstmts, &CHKassign, &CHKfuncall, &CHKif, &CHKwhile, &CHKdowhile,
     &CHKfor, &CHKreturn, &CHKexprs, &CHKbinop, &CHKmonop, &CHKcast, &CHKnum,
     &CHKfloat, &CHKbool, &CHKsymboltable, &CHKsymboltableentry, &CHKerror}

  /* TR_ms */
  , {&TRAVerror, &TRAVsons, &MSfundefdec, &TRAVsons, &TRAVsons, &TRAVsons,
     &MSglobaldec, &MSglobaldef, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &MSfor, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL
};

const char *travnames[6] = {
  "unknown", "prt", "copy", "free", "chk", "ms"
};
