
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "rename_identifiers.h"
#include "sum_ints.h"
#include "opt_sub.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTdeclarations, &PRTfundec, &PRTfundef, &PRTfunheader,
     &PRTfunbody, &PRTvardecs, &PRTvardec, &PRTlocalfundefs, &PRTglobaldec,
     &PRTglobaldef, &PRTparams, &PRTparam, &PRTid, &PRTstmts, &PRTassign,
     &PRTfuncall, &PRTif, &PRTwhile, &PRTfor, &PRTreturn, &PRTexprs,
     &PRTbinop, &PRTmonop, &PRTcast, &PRTnum, &PRTfloat, &PRTbool, &PRTerror}

  /* TR_copy */
  , {&TRAVerror, &COPYdeclarations, &COPYfundec, &COPYfundef, &COPYfunheader,
     &COPYfunbody, &COPYvardecs, &COPYvardec, &COPYlocalfundefs,
     &COPYglobaldec, &COPYglobaldef, &COPYparams, &COPYparam, &COPYid,
     &COPYstmts, &COPYassign, &COPYfuncall, &COPYif, &COPYwhile, &COPYfor,
     &COPYreturn, &COPYexprs, &COPYbinop, &COPYmonop, &COPYcast, &COPYnum,
     &COPYfloat, &COPYbool, &COPYerror}

  /* TR_free */
  , {&TRAVerror, &FREEdeclarations, &FREEfundec, &FREEfundef, &FREEfunheader,
     &FREEfunbody, &FREEvardecs, &FREEvardec, &FREElocalfundefs,
     &FREEglobaldec, &FREEglobaldef, &FREEparams, &FREEparam, &FREEid,
     &FREEstmts, &FREEassign, &FREEfuncall, &FREEif, &FREEwhile, &FREEfor,
     &FREEreturn, &FREEexprs, &FREEbinop, &FREEmonop, &FREEcast, &FREEnum,
     &FREEfloat, &FREEbool, &FREEerror}

  /* TR_chk */
  , {&TRAVerror, &CHKdeclarations, &CHKfundec, &CHKfundef, &CHKfunheader,
     &CHKfunbody, &CHKvardecs, &CHKvardec, &CHKlocalfundefs, &CHKglobaldec,
     &CHKglobaldef, &CHKparams, &CHKparam, &CHKid, &CHKstmts, &CHKassign,
     &CHKfuncall, &CHKif, &CHKwhile, &CHKfor, &CHKreturn, &CHKexprs,
     &CHKbinop, &CHKmonop, &CHKcast, &CHKnum, &CHKfloat, &CHKbool, &CHKerror}

  /* TR_ri */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_si */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &SInum, &TRAVsons, &TRAVsons, &TRAVsons}

  /* TR_os */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &OSbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

const char *travnames[8] = {
  "unknown", "prt", "copy", "free", "chk", "ri", "si", "os"
};
