
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 28
typedef enum
{ N_undefined = 0, N_declarations = 1, N_fundec = 2, N_fundef =
    3, N_funheader = 4, N_funbody = 5, N_vardecs = 6, N_vardec =
    7, N_localfundefs = 8, N_globaldec = 9, N_globaldef = 10, N_params =
    11, N_param = 12, N_id = 13, N_stmts = 14, N_assign = 15, N_funcall =
    16, N_if = 17, N_while = 18, N_for = 19, N_return = 20, N_exprs =
    21, N_binop = 22, N_monop = 23, N_cast = 24, N_num = 25, N_float =
    26, N_bool = 27, N_error = 28 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
