
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 30
typedef enum
{ N_undefined = 0, N_declarations = 1, N_fundec = 2, N_fundef =
    3, N_funheader = 4, N_funbody = 5, N_vardecs = 6, N_vardec =
    7, N_localfundefs = 8, N_localfundef = 9, N_globaldec = 10, N_globaldef =
    11, N_params = 12, N_param = 13, N_id = 14, N_stmts = 15, N_assign =
    16, N_funcall = 17, N_if = 18, N_while = 19, N_dowhile = 20, N_for =
    21, N_return = 22, N_exprs = 23, N_binop = 24, N_monop = 25, N_cast =
    26, N_num = 27, N_float = 28, N_bool = 29, N_error = 30 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
